import { useEffect, useRef, useState } from "react";
import { activateVideoScriptVersion, createQwenVideoScriptJob, createVideoScriptVersion, getQwenVideoScriptJob, getVideoScriptVersion, listVideoScriptVersions, preflightQwenVideoScript, preflightVideoScript } from "../../api/videoScriptVersions";
import type { BatchVideoVariant } from "../../types/batchVideo";
import type { QwenScriptJob, QwenScriptPreflight, QwenScriptPreflightRequest, VideoScriptDraft, VideoScriptVersion } from "../../types/videoScriptVersion";
import { activateExactScript, compareExactVersions, confirmAndCreateQwenJob, pollQwenJobSerial, qwenCostLabel, recoverExactQwenJob, recoverExactScript, replaceScriptOperation, runLatestScriptOperation, saveScriptVersion, scriptCostLabel, scriptReviewLabel, totalSceneDurationMs, type QwenScriptApi, type ScriptApi, type ScriptOperation } from "./videoScriptVersionState";

const api: ScriptApi = { preflight: preflightVideoScript, create: createVideoScriptVersion, list: listVideoScriptVersions, get: getVideoScriptVersion, activate: activateVideoScriptVersion };
const qwenApi: QwenScriptApi = { preflight: preflightQwenVideoScript, create: createQwenVideoScriptJob, readJob: getQwenVideoScriptJob, readVersion: getVideoScriptVersion };
const initialDraft = (): VideoScriptDraft => ({ source_type:"MANUAL", idempotency_key:`manual-${Date.now()}`, parent_version_id:null, strategy_id:null, copy_matrix_id:null, source_video_project_id:null, title:"", concept:"", hook:"", cta:"", scenes:[{ sequence:1,start_ms:0,end_ms:15000,shot_type:"product",visual_description:"",action_description:"",narration:"",subtitle_draft:"" }] });

export function VideoScriptVersionPanel({ variant, onClose, qwenEnabled = false }: { variant: BatchVideoVariant; onClose: () => void; qwenEnabled?: boolean }) {
  const [versions,setVersions]=useState<VideoScriptVersion[]>([]); const [draft,setDraft]=useState(initialDraft); const [message,setMessage]=useState(""); const [compareIds,setCompareIds]=useState<number[]>([]);
  const current=useRef<ScriptOperation|null>(null); const sequence=useRef(0);
  const qwenPoll=useRef<AbortController|null>(null);
  const [qwenRequest,setQwenRequest]=useState<QwenScriptPreflightRequest>({idempotency_key:`qwen-${Date.now()}`,strategy_id:0,copy_matrix_id:null,parent_version_id:variant.active_script_version_id});
  const [qwenChecked,setQwenChecked]=useState<QwenScriptPreflight|null>(null); const [qwenConfirmed,setQwenConfirmed]=useState(false); const [qwenJob,setQwenJob]=useState<QwenScriptJob|null>(null); const [qwenJobId,setQwenJobId]=useState("");
  const begin=()=>replaceScriptOperation(current,++sequence.current,variant.id);
  const refresh=async()=>{ const operation=begin(); await runLatestScriptOperation({operation,current:()=>current.current,execute:(signal)=>recoverExactScript(api,variant.id,variant.active_script_version_id,signal),success:(result)=>setVersions(result.versions),failure:()=>setMessage("Backend连接中断；没有假定版本状态。")}); };
  useEffect(()=>{ void refresh(); return()=>{current.current?.controller.abort();qwenPoll.current?.abort();}; },[variant.id]);
  const save=async()=>{ const operation=begin(); await runLatestScriptOperation({operation,current:()=>current.current,execute:(signal)=>saveScriptVersion(api,variant.id,draft,signal),success:(result)=>{setMessage(result.reused?"已恢复同一幂等版本。":"已保存不可变新版本；审核状态UNREVIEWED。");setDraft({...draft,parent_version_id:result.version.id,idempotency_key:`manual-${Date.now()}`});setVersions((items)=>[...items.filter(x=>x.id!==result.version.id),result.version].sort((a,b)=>a.version_number-b.version_number));},failure:()=>setMessage("Preflight或保存失败；未假定已创建。")}); };
  const activate=async(id:number)=>{ const operation=begin(); await runLatestScriptOperation({operation,current:()=>current.current,execute:(signal)=>activateExactScript(api,variant.id,id,signal),success:()=>setMessage(`已激活精确Version ${id}。`),failure:()=>setMessage("激活失败；指针状态未知，请刷新。")}); };
  const compared=compareIds.length===2?compareExactVersions(versions.find(x=>x.id===compareIds[0])!,versions.find(x=>x.id===compareIds[1])!):null;
  const set=(field:keyof VideoScriptDraft,value:unknown)=>setDraft((old)=>({...old,[field]:value}));
  const beginQwenPolling=(jobId:number)=>{qwenPoll.current?.abort();const controller=new AbortController();qwenPoll.current=controller;void pollQwenJobSerial({api:qwenApi,variantId:variant.id,jobId,signal:controller.signal,delay:(signal)=>new Promise(resolve=>{const timer=window.setTimeout(resolve,1000);signal.addEventListener("abort",()=>{window.clearTimeout(timer);resolve();},{once:true});}),update:(job,version)=>{setQwenJob(job);if(version)setVersions(items=>[...items.filter(item=>item.id!==version.id),version].sort((a,b)=>a.version_number-b.version_number));if(job.status==="SUBMIT_UNKNOWN")setMessage("Qwen提交状态不确定，禁止自动重试。");else if(job.status==="FAILED")setMessage("Qwen生成明确失败；未创建脚本版本。");else if(job.status==="SUCCEEDED")setMessage(`Qwen生成成功：Version ${job.result_entity_id}，仍为UNREVIEWED且未自动激活。`);},failure:()=>setMessage("Backend连接中断；轮询已停止，可按精确Job ID恢复。")});};
  const qwenPreflight=async()=>{const operation=begin();await runLatestScriptOperation({operation,current:()=>current.current,execute:(signal)=>qwenApi.preflight(variant.id,qwenRequest,signal),success:(checked)=>{setQwenChecked(checked);setQwenConfirmed(false);setMessage(checked.ready_for_execution?"Qwen Preflight完成；Provider调用0。":"费用或配额未就绪，不能入队。");},failure:()=>setMessage("Qwen Preflight失败；没有创建Job。")});};
  const qwenSubmit=async()=>{if(!qwenChecked)return;const operation=begin();await runLatestScriptOperation({operation,current:()=>current.current,execute:(signal)=>confirmAndCreateQwenJob(qwenApi,variant.id,qwenRequest,qwenChecked,qwenConfirmed,signal),success:({checked,created})=>{setQwenChecked(checked);setQwenJob(created.job);setQwenJobId(String(created.job.id));setMessage(created.reused?"已恢复相同Qwen Job。":"Qwen Job已入队；HTTP Provider调用0。");beginQwenPolling(created.job.id);},failure:()=>setMessage("费用确认或入队失败；未假定Job已创建。")});};
  const qwenRecover=async()=>{const id=Number(qwenJobId);if(!Number.isInteger(id)||id<=0)return;const operation=begin();await runLatestScriptOperation({operation,current:()=>current.current,execute:(signal)=>recoverExactQwenJob(qwenApi,variant.id,id,signal),success:({job,version})=>{setQwenJob(job);if(version)setVersions(items=>[...items.filter(item=>item.id!==version.id),version].sort((a,b)=>a.version_number-b.version_number));if(job.status==="QUEUED"||job.status==="RUNNING")beginQwenPolling(job.id);},failure:()=>setMessage("无法恢复该精确Job ID。")});};
  return <section className="video-script-panel"><header><span>STAGE 3D · PROVIDER-FREE</span><h2>Variant {variant.id} 脚本版本</h2><button onClick={onClose}>关闭</button></header><p>Batch {variant.batch_video_job_id} · Product {variant.product_id} · {variant.platform} #{variant.variant_index} · {scriptCostLabel("manual_versioning_only")} · {scriptReviewLabel("UNREVIEWED")}</p>
    <label>来源<select value={draft.source_type} onChange={e=>set("source_type",e.target.value)}><option>MANUAL</option><option>VIDEO_PROJECT_IMPORT</option></select></label>{draft.source_type==="VIDEO_PROJECT_IMPORT"&&<label>精确VideoProject ID<input type="number" onChange={e=>set("source_video_project_id",Number(e.target.value)||null)}/></label>}
    {(["title","concept","hook","cta"] as const).map(field=><label key={field}>{field}<textarea value={draft[field]} onChange={e=>set(field,e.target.value)}/></label>)}
    {draft.scenes.map((scene,index)=><fieldset key={scene.sequence}><legend>镜头 {scene.sequence}</legend>{(["start_ms","end_ms"] as const).map(field=><input key={field} type="number" value={scene[field]} onChange={e=>set("scenes",draft.scenes.map((x,i)=>i===index?{...x,[field]:Number(e.target.value)}:x))}/>)}{(["shot_type","visual_description","action_description","narration","subtitle_draft"] as const).map(field=><textarea key={field} aria-label={field} value={scene[field]} onChange={e=>set("scenes",draft.scenes.map((x,i)=>i===index?{...x,[field]:e.target.value}:x))}/>)}</fieldset>)}
    <p>时长合计：{totalSceneDurationMs(draft)/1000}秒</p><button disabled={totalSceneDurationMs(draft)!==15000} onClick={()=>void save()}>Preflight并保存新版本</button>{message&&<p role="status">{message}</p>}
    {qwenEnabled&&<fieldset><legend>Stage 3E · 单Variant Qwen生成</legend><p>生成后不会自动启用；结果固定为UNREVIEWED，需人工比较后激活。</p><label>精确Strategy ID<input type="number" value={qwenRequest.strategy_id||""} onChange={e=>setQwenRequest(old=>({...old,strategy_id:Number(e.target.value)||0}))}/></label><label>可选CopyMatrix ID<input type="number" onChange={e=>setQwenRequest(old=>({...old,copy_matrix_id:Number(e.target.value)||null}))}/></label><label>可选Parent Version ID<input type="number" value={qwenRequest.parent_version_id??""} onChange={e=>setQwenRequest(old=>({...old,parent_version_id:Number(e.target.value)||null}))}/></label><button disabled={qwenRequest.strategy_id<=0} onClick={()=>void qwenPreflight()}>Qwen Provider-free Preflight</button>{qwenChecked&&<><p>预计调用：1次 · 费用：{qwenCostLabel(qwenChecked)} · 配额剩余：{qwenChecked.quota_remaining}</p><label><input type="checkbox" checked={qwenConfirmed} onChange={e=>setQwenConfirmed(e.target.checked)}/>我确认此精确输入的费用区间</label><button disabled={!qwenConfirmed||!qwenChecked.ready_for_execution} onClick={()=>void qwenSubmit()}>确认并入队</button></>}<div><input aria-label="精确Qwen Job ID" value={qwenJobId} onChange={e=>setQwenJobId(e.target.value)}/><button onClick={()=>void qwenRecover()}>按Job ID恢复</button></div>{qwenJob&&<p>Job {qwenJob.id} · {qwenJob.status}{qwenJob.result_entity_id?` · Version ${qwenJob.result_entity_id}`:""}</p>}</fieldset>}
    <h3>升序版本历史</h3>{versions.map(version=><div key={version.id}><label><input type="checkbox" checked={compareIds.includes(version.id)} onChange={e=>setCompareIds(ids=>e.target.checked?[...ids,version.id].slice(-2):ids.filter(id=>id!==version.id))}/>V{version.version_number} · ID {version.id} · {version.source_type} · {version.review_status}</label><button onClick={()=>void activate(version.id)}>激活</button></div>)}{compared&&<pre>{JSON.stringify(compared,null,2)}</pre>}</section>;
}
