import { useEffect, useRef, useState } from "react";
import { activateVideoScriptVersion, createVideoScriptVersion, getVideoScriptVersion, listVideoScriptVersions, preflightVideoScript } from "../../api/videoScriptVersions";
import type { BatchVideoVariant } from "../../types/batchVideo";
import type { VideoScriptDraft, VideoScriptVersion } from "../../types/videoScriptVersion";
import { activateExactScript, compareExactVersions, recoverExactScript, replaceScriptOperation, runLatestScriptOperation, saveScriptVersion, scriptCostLabel, scriptReviewLabel, totalSceneDurationMs, type ScriptApi, type ScriptOperation } from "./videoScriptVersionState";

const api: ScriptApi = { preflight: preflightVideoScript, create: createVideoScriptVersion, list: listVideoScriptVersions, get: getVideoScriptVersion, activate: activateVideoScriptVersion };
const initialDraft = (): VideoScriptDraft => ({ source_type:"MANUAL", idempotency_key:`manual-${Date.now()}`, parent_version_id:null, strategy_id:null, copy_matrix_id:null, source_video_project_id:null, title:"", concept:"", hook:"", cta:"", scenes:[{ sequence:1,start_ms:0,end_ms:15000,shot_type:"product",visual_description:"",action_description:"",narration:"",subtitle_draft:"" }] });

export function VideoScriptVersionPanel({ variant, onClose }: { variant: BatchVideoVariant; onClose: () => void }) {
  const [versions,setVersions]=useState<VideoScriptVersion[]>([]); const [draft,setDraft]=useState(initialDraft); const [message,setMessage]=useState(""); const [compareIds,setCompareIds]=useState<number[]>([]);
  const current=useRef<ScriptOperation|null>(null); const sequence=useRef(0);
  const begin=()=>replaceScriptOperation(current,++sequence.current,variant.id);
  const refresh=async()=>{ const operation=begin(); await runLatestScriptOperation({operation,current:()=>current.current,execute:(signal)=>recoverExactScript(api,variant.id,variant.active_script_version_id,signal),success:(result)=>setVersions(result.versions),failure:()=>setMessage("Backend连接中断；没有假定版本状态。")}); };
  useEffect(()=>{ void refresh(); return()=>current.current?.controller.abort(); },[variant.id]);
  const save=async()=>{ const operation=begin(); await runLatestScriptOperation({operation,current:()=>current.current,execute:(signal)=>saveScriptVersion(api,variant.id,draft,signal),success:(result)=>{setMessage(result.reused?"已恢复同一幂等版本。":"已保存不可变新版本；审核状态UNREVIEWED。");setDraft({...draft,parent_version_id:result.version.id,idempotency_key:`manual-${Date.now()}`});setVersions((items)=>[...items.filter(x=>x.id!==result.version.id),result.version].sort((a,b)=>a.version_number-b.version_number));},failure:()=>setMessage("Preflight或保存失败；未假定已创建。")}); };
  const activate=async(id:number)=>{ const operation=begin(); await runLatestScriptOperation({operation,current:()=>current.current,execute:(signal)=>activateExactScript(api,variant.id,id,signal),success:()=>setMessage(`已激活精确Version ${id}。`),failure:()=>setMessage("激活失败；指针状态未知，请刷新。")}); };
  const compared=compareIds.length===2?compareExactVersions(versions.find(x=>x.id===compareIds[0])!,versions.find(x=>x.id===compareIds[1])!):null;
  const set=(field:keyof VideoScriptDraft,value:unknown)=>setDraft((old)=>({...old,[field]:value}));
  return <section className="video-script-panel"><header><span>STAGE 3D · PROVIDER-FREE</span><h2>Variant {variant.id} 脚本版本</h2><button onClick={onClose}>关闭</button></header><p>Batch {variant.batch_video_job_id} · Product {variant.product_id} · {variant.platform} #{variant.variant_index} · {scriptCostLabel("manual_versioning_only")} · {scriptReviewLabel("UNREVIEWED")}</p>
    <label>来源<select value={draft.source_type} onChange={e=>set("source_type",e.target.value)}><option>MANUAL</option><option>VIDEO_PROJECT_IMPORT</option></select></label>{draft.source_type==="VIDEO_PROJECT_IMPORT"&&<label>精确VideoProject ID<input type="number" onChange={e=>set("source_video_project_id",Number(e.target.value)||null)}/></label>}
    {(["title","concept","hook","cta"] as const).map(field=><label key={field}>{field}<textarea value={draft[field]} onChange={e=>set(field,e.target.value)}/></label>)}
    {draft.scenes.map((scene,index)=><fieldset key={scene.sequence}><legend>镜头 {scene.sequence}</legend>{(["start_ms","end_ms"] as const).map(field=><input key={field} type="number" value={scene[field]} onChange={e=>set("scenes",draft.scenes.map((x,i)=>i===index?{...x,[field]:Number(e.target.value)}:x))}/>)}{(["shot_type","visual_description","action_description","narration","subtitle_draft"] as const).map(field=><textarea key={field} aria-label={field} value={scene[field]} onChange={e=>set("scenes",draft.scenes.map((x,i)=>i===index?{...x,[field]:e.target.value}:x))}/>)}</fieldset>)}
    <p>时长合计：{totalSceneDurationMs(draft)/1000}秒</p><button disabled={totalSceneDurationMs(draft)!==15000} onClick={()=>void save()}>Preflight并保存新版本</button>{message&&<p role="status">{message}</p>}
    <h3>升序版本历史</h3>{versions.map(version=><div key={version.id}><label><input type="checkbox" checked={compareIds.includes(version.id)} onChange={e=>setCompareIds(ids=>e.target.checked?[...ids,version.id].slice(-2):ids.filter(id=>id!==version.id))}/>V{version.version_number} · ID {version.id} · {version.review_status}</label><button onClick={()=>void activate(version.id)}>激活</button></div>)}{compared&&<pre>{JSON.stringify(compared,null,2)}</pre>}</section>;
}
